services:
  experiment_service:
    build: .
    container_name: experiment_service
    env_file: ./.env
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - public_network
    volumes:
      - ./experiments:/app/experiments
      - ./output:/app/output
      - ./generated_tests:/app/generated_tests
      - ./models:/app/models
      - ./results:/app/results
      - ${SF110_PATH}:/data/sf110

networks:
  public_network:
    driver: bridge
