"""
Model Manager — Manages local and remote LLMs for Java test generation.

Usage:
    from model_manager import ModelManager
    manager = ModelManager()

    # Local model (default)
    code = manager.run_from_file("Qwen_Qwen3-0.5B", "output/prompt.txt")

    # Remote model via OpenRouter
    code = manager.run_from_file("openai/gpt-4o", "output/prompt.txt", backend="remote")
"""

import gc
import json
import os
import re
import time
import requests
from pathlib import Path

from transformers import AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import snapshot_download
from dotenv import load_dotenv
from prompt_manager import PromptManager

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
BASE_DIR = Path(__file__).resolve().parent


class ModelManager:
    """Manages local LLMs for test generation from extractor-produced prompts."""

    def __init__(self):
        self.models_dir = BASE_DIR / "models"
        self._loaded_model_name = None
        self._model = None
        self._tokenizer = None

    def download_model(self, hf_model_id: str) -> Path:
        """Downloads a model from Hugging Face and saves it under models/."""
        if not HF_TOKEN:
            raise ValueError("HF_TOKEN is not set in environment variables.")

        self.models_dir.mkdir(exist_ok=True)
        target_dir = self.models_dir / hf_model_id.replace("/", "_")

        if target_dir.exists():
            print(f"Model already exists at {target_dir}")
            return target_dir

        print(f"Downloading model {hf_model_id}...")
        snapshot_download(repo_id=hf_model_id, local_dir=target_dir, token=HF_TOKEN)
        return target_dir

    def run_model(self, model_name: str, prompt: str, backend: str = "local") -> str:
        """Generates text from the prompt using a local or remote model.

        Args:
            model_name: Local model directory name (backend="local") or
                        OpenRouter model ID such as "openai/gpt-4o" (backend="remote").
            prompt: Input text for the model.
            backend: Execution backend — "local" (default) or "remote" (OpenRouter).

        Returns:
            Text generated by the model.
        """
        if backend == "remote":
            return self._run_model_remote(model_name, prompt)
        return self._run_model_local(model_name, prompt)

    def _run_model_local(self, model_name: str, prompt: str) -> str:
        """Loads a local HuggingFace model and generates text from the prompt."""
        import torch

        model_path = self.models_dir / model_name

        if not model_path.exists():
            raise ValueError(f"Model not found at {model_path}")

        if self._loaded_model_name != model_name:
            self._model = None
            self._tokenizer = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            print(f"Loading model from {model_path}...")
            self._tokenizer = AutoTokenizer.from_pretrained(str(model_path))
            self._model = AutoModelForCausalLM.from_pretrained(
                str(model_path),
                dtype="auto",
                device_map="auto",
            )
            self._loaded_model_name = model_name

        print("Running model...")
        system_prompt = PromptManager().get_system_prompt()
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]
        text = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
        model_inputs = self._tokenizer([text], return_tensors="pt").to(self._model.device)

        generated_ids = self._model.generate(
            **model_inputs,
            max_new_tokens=2048,
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

        content = self._tokenizer.decode(output_ids, skip_special_tokens=True).strip("\n")
        return content

    def _run_model_remote(self, model_name: str, prompt: str) -> str:
        """Calls an OpenRouter model via the chat completions API.

        Args:
            model_name: OpenRouter model ID (e.g. "openai/gpt-4o", "anthropic/claude-3.5-sonnet").
            prompt: Input text for the model.

        Returns:
            Text generated by the remote model.
        """
        if not OPENROUTER_API_KEY:
            raise ValueError("OPENROUTER_API_KEY is not set in environment variables.")

        system_prompt = PromptManager().get_system_prompt()
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]

        print(f"Running remote model '{model_name}' via OpenRouter...")
        max_retries = 5
        delay = 10  # seconds; doubles on each 429
        for attempt in range(1, max_retries + 1):
            response = requests.post(
                url=OPENROUTER_BASE_URL,
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                },
                data=json.dumps({
                    "model": model_name,
                    "messages": messages,
                    "max_tokens": 2048,
                }),
                timeout=120,
            )
            if response.status_code == 429:
                retry_after = int(response.headers.get("Retry-After", delay))
                wait = max(retry_after, delay)
                print(f"  Rate limited (429). Waiting {wait}s before retry {attempt}/{max_retries}...")
                time.sleep(wait)
                delay *= 2
                continue
            response.raise_for_status()
            payload = response.json()
            return payload["choices"][0]["message"]["content"].strip("\n")

        raise RuntimeError(f"OpenRouter rate limit persisted after {max_retries} retries for model '{model_name}'.")

    def extract_java_code(self, raw_output: str) -> str:
        """Extracts only the Java code from the model's raw output."""
        fenced = re.search(r"```(?:java)?\s*\n(.*?)```", raw_output, re.DOTALL)
        if fenced:
            return fenced.group(1).strip()

        java_start = re.search(
            r"^(import\s+[\w.]+;|public\s|class\s|interface\s|enum\s|@[\w]+)",
            raw_output,
            re.MULTILINE,
        )
        if java_start:
            return raw_output[java_start.start():].strip()

        return raw_output.strip()

    def run_from_file(self, model_name: str, prompt_file: str, output_file: str = None,
                      backend: str = "local") -> str:
        """Reads a prompt from a .txt file and runs it through the model.

        Args:
            model_name: Model directory name (local) or OpenRouter model ID (remote).
            prompt_file: Path to the .txt prompt file (e.g. output/0007_DocumentSet_wordFrequency.txt).
            output_file: Optional path to save the generated code.
            backend: Execution backend — "local" (default) or "remote" (OpenRouter).

        Returns:
            Generated Java code.
        """
        prompt_path = Path(prompt_file)
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_file}")

        prompt = prompt_path.read_text(encoding="utf-8")
        raw_output = self.run_model(model_name, prompt, backend=backend)
        code = self.extract_java_code(raw_output)

        if output_file:
            out_path = Path(output_file)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(code, encoding="utf-8")
            print(f"Code saved to {out_path}")

        return code

    def run_batch(self, model_name: str, input_dir: str, output_dir: str, max_files: int = 100,
                  backend: str = "local", concurrency: int = 20, skip_missing_sut: bool = False):
        """Runs the model over all .txt prompt files in a directory.

        Each generated test is saved to:
            <output_dir>/<sut_project>/<FocalClass>_<focalMethod>_<hash>/test.java

        A metadata.json is also saved alongside each test.java with fields required
        by the evaluation pipeline. SUT information is read from batch_metadata.json
        in the input directory (produced by batch_extract).

        Args:
            model_name: Model directory name (local) or OpenRouter model ID (remote).
            input_dir: Directory containing .txt prompt files.
            output_dir: Output directory for generated tests.
            max_files: Maximum number of files to process.
            backend: Execution backend — "local" (default) or "remote" (OpenRouter).
            concurrency: Number of parallel workers for remote backend (default: 20).
            skip_missing_sut: If True, skip prompts whose SUT JAR is not in ~/.m2.
        """
        import hashlib
        import threading
        from concurrent.futures import ThreadPoolExecutor, as_completed
        from datetime import datetime

        m2_repo = Path.home() / ".m2" / "repository"

        in_path = Path(input_dir)
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        batch_meta_path = in_path / "batch_metadata.json"
        batch_meta_by_file: dict = {}
        if batch_meta_path.exists():
            with open(batch_meta_path, encoding="utf-8") as f:
                for entry in json.load(f):
                    batch_meta_by_file[entry["prompt_file"]] = entry

        def _resolve_artifact_id(meta_entry: dict) -> str:
            source_path = meta_entry.get("source_path", "")
            base_path_str = meta_entry.get("base_path", "")
            if source_path and base_path_str:
                try:
                    return Path(source_path).relative_to(base_path_str).parts[0]
                except (ValueError, IndexError):
                    parts = Path(source_path).parts
                    return parts[-4] if len(parts) >= 4 else "unknown"
            return "unknown"

        all_files = sorted(in_path.glob("*.txt"))[:max_files]

        if skip_missing_sut:
            prompt_files = []
            skipped_upfront = []
            for pf in all_files:
                artifact_id = _resolve_artifact_id(batch_meta_by_file.get(pf.name, {}))
                jar = m2_repo / "sf110" / artifact_id / "1.0" / f"{artifact_id}-1.0.jar"
                if artifact_id == "unknown" or jar.exists():
                    prompt_files.append(pf)
                else:
                    skipped_upfront.append(pf.name)
            print(f"[Batch] --skip-missing-sut: {len(skipped_upfront)} prompts skipped (JAR not in ~/.m2), {len(prompt_files)} will be processed")
        else:
            prompt_files = all_files

        results = []
        print_lock = threading.Lock()

        def process_file(idx: int, pf: Path) -> dict:
            meta_entry = batch_meta_by_file.get(pf.name, {})
            sut_artifact_id = _resolve_artifact_id(meta_entry)

            with print_lock:
                print(f"\n[{idx + 1}/{len(prompt_files)}] Processing {pf.name}...")
            try:
                code = self.run_from_file(model_name, str(pf), backend=backend)

                source_path = meta_entry.get("source_path", "")
                package = meta_entry.get("package", "")
                focal_class = meta_entry.get("class", pf.stem.split("_")[1] if "_" in pf.stem else pf.stem)
                focal_class_simple = focal_class.split(".")[-1] if focal_class else pf.stem
                focal_method = meta_entry.get("method", "unknown")

                uid = hashlib.md5(f"{model_name}:{pf.name}".encode()).hexdigest()[:8]
                test_dir_name = f"{focal_class_simple}_{focal_method}_{uid}"
                test_dir = out_path / sut_artifact_id / test_dir_name
                test_dir.mkdir(parents=True, exist_ok=True)

                test_java_path = test_dir / "test.java"
                test_java_path.write_text(code, encoding="utf-8")

                metadata = {
                    "sut_project":     sut_artifact_id,
                    "sut_class_path":  source_path,
                    "sut_package":     package,
                    "sut_artifact_id": sut_artifact_id,
                    "focal_method":    focal_method,
                    "focal_class":     focal_class_simple,
                    "model":           model_name,
                    "prompt_type":     meta_entry.get("prompt_type", "zero_shot"),
                    "generated_at":    datetime.now().isoformat(timespec="seconds"),
                }
                metadata_path = test_dir / "metadata.json"
                with open(metadata_path, "w", encoding="utf-8") as f:
                    json.dump(metadata, f, indent=2, ensure_ascii=False)

                with print_lock:
                    print(f"  [{pf.name}] Saved to {test_dir}")
                return {
                    "file": pf.name,
                    "output": str(test_java_path),
                    "test_dir": str(test_dir),
                    "status": "ok",
                    "length": len(code),
                }
            except Exception as e:
                with print_lock:
                    print(f"  [{pf.name}] ERROR: {e}")
                return {"file": pf.name, "status": "error", "error": str(e)}

        if backend == "remote":
            workers = min(concurrency, len(prompt_files)) if prompt_files else 1
            with ThreadPoolExecutor(max_workers=workers) as executor:
                futures = {executor.submit(process_file, i, pf): pf for i, pf in enumerate(prompt_files)}
                for future in as_completed(futures):
                    results.append(future.result())
        else:
            for i, pf in enumerate(prompt_files):
                results.append(process_file(i, pf))

        results.sort(key=lambda r: r["file"])

        meta_path = out_path / "batch_results.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

        ok = sum(1 for r in results if r["status"] == "ok")
        print(f"\n[Batch] {ok}/{len(prompt_files)} tests generated in '{output_dir}'")
        print(f"[Batch] Metadata: {meta_path}")
