from huggingface_hub import HfApi, snapshot_download
import os 
from pathlib import Path
from transformers import AutoModelForCausalLM, AutoTokenizer
from dotenv import load_dotenv
load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")

class ModelManager:
    """
    Manages the models.
    """
    
    def __init__(self):
        self.BASE_DIR = Path(__file__).resolve().parent
        self._loaded_model_name = None
        self._model = None
        self._tokenizer = None

    def list_hf_models(self):
        """Lists all available models in the authenticated Hugging Face account."""
        if not HF_TOKEN:
            raise ValueError("Hugging Face token (HF_TOKEN) is not set in environment variables.")
        
        api = HfApi(token=HF_TOKEN)
        models = api.list_models()
        return [model.modelId for model in models]

    def download_model(self, hf_model_id):
        """Downloads a model from Hugging Face and saves it locally in the models/ folder.

        Args:
            hf_model_id: Model ID on Hugging Face (e.g. 'Qwen/Qwen2.5-Coder-0.5B-Instruct').

        Returns:
            Path of the directory where the model was saved.
        """
        if not HF_TOKEN:
            raise ValueError("Hugging Face token (HF_TOKEN) is not set in environment variables.")
        
        MODELS_DIR = self.BASE_DIR / "models"
        MODELS_DIR.mkdir(exist_ok=True)

        target_dir = MODELS_DIR / hf_model_id.replace("/", "_")
        
        if target_dir.exists():
            print(f"Model {hf_model_id} already downloaded at {target_dir}")
            return target_dir
        
        print(f"Downloading model {hf_model_id}...")
        snapshot_download(repo_id=hf_model_id, local_dir=target_dir, token=HF_TOKEN)

        return target_dir

    def delete_model(self, model_name):
        """Removes a locally saved model from the models/ folder.

        Args:
            model_name: Name of the model directory inside models/.
        """
        MODEL_PATH = os.path.join(self.BASE_DIR, "models", model_name)
        
        if not os.path.exists(MODEL_PATH):
            print(f"Model {model_name} does not exist at {MODEL_PATH}")
            return
        
        os.rmdir(MODEL_PATH)
        print(f"Model {model_name} deleted from {MODEL_PATH}")

    def run_model(self, model_name, prompt) -> str:
        """Loads a locally saved model and runs text generation from a prompt.

        Caches the loaded model in the instance so it is not reloaded on every
        call. If a different model is requested, the previous one is released
        from memory before loading the new one.

        Uses chat-template formatting and parses thinking content separately
        (compatible with Qwen3 thinking mode and other chat models).

        Args:
            model_name: Name of the model directory inside models/.
            prompt: Input text for the model.

        Returns:
            Text generated by the model (thinking content excluded).

        Raises:
            ValueError: If the model does not exist in the models/ directory.
        """
        import gc
        import torch

        MODEL_PATH = os.path.join(self.BASE_DIR, "models", model_name)

        if not os.path.exists(MODEL_PATH):
            raise ValueError(f"Model {model_name} does not exist at {MODEL_PATH}")

        if self._loaded_model_name != model_name:
            self._model = None
            self._tokenizer = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            print(f"Loading model from {MODEL_PATH}...")
            self._tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
            self._model = AutoModelForCausalLM.from_pretrained(
                MODEL_PATH,
                dtype="auto",
                device_map="auto",
            )
            self._loaded_model_name = model_name

        print("Running model...")
        print("Prompt:\n", prompt)

        messages = [{"role": "user", "content": prompt}]
        text = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=True,
        )
        model_inputs = self._tokenizer([text], return_tensors="pt").to(self._model.device)

        generated_ids = self._model.generate(
            **model_inputs,
            max_new_tokens=2048,
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist()

        # Parse out thinking content (tokens before </think> token id 151668)
        try:
            index = len(output_ids) - output_ids[::-1].index(151668)
        except ValueError:
            index = 0

        content = self._tokenizer.decode(output_ids[index:], skip_special_tokens=True).strip("\n")
        return content


    def prone_code_generated(self, code) -> str:
        """Identifies the generated Java code and removes any surrounding extra text.

        Args:
            code: Raw text returned by the model, which may contain explanations or extra formatting.

        Returns:
            Only the extracted Java code block.
        """
        import re

        # Try to extract code from markdown fenced blocks (```java ... ``` or ``` ... ```)
        fenced_match = re.search(r"```(?:java)?\s*\n(.*?)```", code, re.DOTALL)
        if fenced_match:
            return fenced_match.group(1).strip()

        # Fallback: find the first Java-like construct and return from there
        java_start = re.search(
            r"^(import\s+[\w.]+;|public\s|class\s|interface\s|enum\s|@[\w]+)",
            code,
            re.MULTILINE,
        )
        if java_start:
            return code[java_start.start():].strip()

        return code.strip()
    
    def save_code_to_file(self, code: str, file_path: str):
        """Saves the generated code to a file at the specified path.

        Args:
            code: Code to be saved.
            file_path: Full path of the destination file (e.g. 'output/MyClass.java').
        """
        path = Path(file_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(code)

        print(f"Code saved to {path}")


# -------------------------
# Example usage:
# -------------------------
# if __name__ == "__main__":
#     manager = ModelManager()
#     models = manager.list_hf_models()
#     manager.download_model("Qwen/Qwen2.5-Coder-0.5B-Instruct")
    
#     prompt = "Write a fibonacci function in Java. Return only the code, without explanations."
#     response = manager.run_model("Qwen_Qwen2.5-Coder-0.5B-Instruct", prompt)
#     proned_code = manager.prone_code_generated(response)
#     manager.save_code_to_file(proned_code, "output/Fibonacci.java")
#     print(proned_code)



"""
 private void initComponents() {
        currentAuthor = new JTextField();
        chooseFile = new JFileChooser();
        menuBar = new JMenuBar();
        menuFile = new JMenu();
        menuFileExit = new JMenuItem();
        menuFileDemo = new JMenuItem();
        menuHelp = new JMenu();
        menuHelpContents = new JMenuItem();
        menuHelpAbout = new JMenuItem();
        paneOpts = new JTabbedPane();
        panelAcquire = new JPanel();
        panelDocs = new JPanel();
        labelKnown = new JLabel();
        scrollPane1 = new JScrollPane();

        listKnown = new JTextArea(10,30);

        labelUnknown = new JLabel();
        scrollPane2 = new JScrollPane();

        listUnknown = new JTextArea(10,30);

        panelOpts = new JPanel();
        radioKnown = new JRadioButton();
        radioUnknown = new JRadioButton();
        buttonLocal = new JButton();
        panelCanonicize = new JPanel();
        panelCOpts = new JPanel();

        canonicizers = new JCheckBox[3];
        eventifiers = new JRadioButton[2];
        esButtonGroup = new ButtonGroup();


        panelProgress = new JPanel();
        buttonCanonicize = new JButton();
        label1 = new JLabel();
        progressCanonicize = new JProgressBar();
        labelCanon = new JLabel();
        panelAnalyze = new JPanel();
        labelStatInf = new JLabel();
        panelMethods = new JPanel();
        radioCrossEnt = new JRadioButton();
        radioLZW = new JRadioButton();
        panelAnalProg = new JPanel();
        buttonAnalyze = new JButton();
        labelAnalProg = new JLabel();
        progressAnalysis = new JProgressBar();
        scrollPane3 = new JScrollPane();

        listResults = new JTextArea(20,30);

        buttonEventSet = new JButton();
        paneEvProgress = new JPanel();
        labelevSet = new JLabel();
        progressEventSet = new JProgressBar();
        panelEventSet = new JPanel();
        panelEOpts = new JPanel();
        panelEvProgress = new JPanel();

         
        setMinimumSize(new Dimension(400, 600));
        setPreferredSize(new Dimension(600, 400));
        setLayout(new BorderLayout());

         
        {
            
             
            {
                menuFile.setText("File");

                 
                menuFileExit.setText("Exit");
                menuFile.add(menuFileExit);
                menuFileExit.addActionListener(this);

                menuFileDemo.setText("Load Demo");
                menuFileDemo.setActionCommand("demo");
                menuFileDemo.addActionListener(this);
                menuFile.add(menuFileDemo);
            
            }
            menuBar.add(menuFile);
            
             
            {
                menuHelp.setText("Help");

                 
                menuHelpContents.setText("Contents (F1)");
                menuHelp.add(menuHelpContents);

                 
                menuHelpAbout.setText("About");
                menuHelp.add(menuHelpAbout);
            }
            menuBar.add(menuHelp);
        }
        add(menuBar, BorderLayout.NORTH);

         
        {
            paneOpts.setFont(new Font("Garamond", Font.PLAIN, 14));
            
             
            {
                panelAcquire.setLayout(new FlowLayout());

                 
                {
                    panelDocs.setLayout(new BoxLayout(panelDocs, BoxLayout.Y_AXIS));
                    
                     
                    labelKnown.setText("Registered Known Documents");
                    labelKnown.setHorizontalAlignment(SwingConstants.CENTER);
                    labelKnown.setHorizontalTextPosition(SwingConstants.CENTER);
                    panelDocs.add(labelKnown);
                    
                    listKnown.setEnabled(false);
                     
                    {
                        scrollPane1.setViewportView(listKnown);
                    }
                    panelDocs.add(scrollPane1);
                    
                     
                    labelUnknown.setText("Registered Unknown Documents");
                    labelUnknown.setHorizontalAlignment(SwingConstants.CENTER);
                    labelUnknown.setHorizontalTextPosition(SwingConstants.CENTER);
                    panelDocs.add(labelUnknown);
                    
                    listUnknown.setEnabled(false);
                     
                    {
                        scrollPane2.setViewportView(listUnknown);
                    }
                    panelDocs.add(scrollPane2);
                }
                panelAcquire.add(panelDocs);

                 
                {
                    panelOpts.setLayout(new BoxLayout(panelOpts, BoxLayout.Y_AXIS));

                     
                    radioUnknown.setText("Unknown Author");
                    radioUnknown.setActionCommand("unknownauthor");
                    radioUnknown.addActionListener(this);
                    panelOpts.add(radioUnknown);
                    
                     
                    radioKnown.setText("Known Author");
                    radioKnown.setActionCommand("knownauthor");
                    radioKnown.addActionListener(this);
                    radioKnown.setSelected(true);
                    panelOpts.add(radioKnown);
                    
                    panelOpts.add(new JLabel("Author:"));
                    
                     
                    panelOpts.add(currentAuthor);
                    
                    
                     
                    buttonLocal.setText("Local Document");
                    panelOpts.add(buttonLocal);
                    buttonLocal.setActionCommand("Import");
                    buttonLocal.addActionListener(this);
                }
                panelAcquire.add(panelOpts);
            }
            paneOpts.addTab("Acquire", panelAcquire);
            
            
             
            {
                panelCanonicize.setLayout(new BorderLayout());

                 
                {
                    panelCOpts.setLayout(new GridLayout(12, 5));
                    
                     
                    canonicizers[0] = new JCheckBox();
                    canonicizers[0].setText("Smash Case");
                    canonicizers[0].setToolTipText("Converts all text to lower case");
                    panelCOpts.add(canonicizers[0]);
                    
                     
                    canonicizers[1] = new JCheckBox();
                    canonicizers[1].setText("Normalize Whitespace");
                    canonicizers[1].setToolTipText("Converts all whitespace characters (newline, space and tab) to a single space");
                    panelCOpts.add(canonicizers[1]);
                    
                     
                    canonicizers[2] = new JCheckBox();
                    canonicizers[2].setText("Strip HTML");
                    canonicizers[2].setToolTipText("Removes all HTML tags and converts hexidecimal representations to actual character representations");
                    panelCOpts.add(canonicizers[2]);
                }
                panelCanonicize.add(panelCOpts, BorderLayout.CENTER);

                 
                {
                    panelProgress.setLayout(new BoxLayout(panelProgress, BoxLayout.X_AXIS));
                    
                     
                    buttonCanonicize.setText("Canonicize");
                    buttonCanonicize.addActionListener(this);
                    panelProgress.add(buttonCanonicize);
                    
                    
                     
                    label1.setText("  Progress:  ");
                    label1.setHorizontalAlignment(SwingConstants.CENTER);
                    label1.setHorizontalTextPosition(SwingConstants.CENTER);
                    panelProgress.add(label1);
                    panelProgress.add(progressCanonicize);
                }
                panelCanonicize.add(panelProgress, BorderLayout.SOUTH);

                 
                labelCanon.setText("Document Canonicization");
                labelCanon.setHorizontalAlignment(SwingConstants.CENTER);
                panelCanonicize.add(labelCanon, BorderLayout.NORTH);
            }
            paneOpts.addTab("Canonicize", panelCanonicize);
            
             
            {
                panelEventSet.setLayout(new BorderLayout());

                 
                {
                    panelEOpts.setLayout(new GridLayout(12,5));

                     
                    eventifiers[0] = new JRadioButton();
                    eventifiers[0].setText("Individual Characters");
                    eventifiers[0].setActionCommand("characters");
                    esButtonGroup.add(eventifiers[0]);
                    panelEOpts.add(eventifiers[0]);

                     
                    eventifiers[1] = new JRadioButton();
                    eventifiers[1].setText("Entire Words");
                    eventifiers[1].setActionCommand("words");
                    esButtonGroup.add(eventifiers[1]);
                    panelEOpts.add(eventifiers[1]);
                    
                }
                panelEventSet.add(panelEOpts,BorderLayout.CENTER);

                 
                {              
                    panelEvProgress.setLayout(new BoxLayout(panelEvProgress, BoxLayout.X_AXIS));
                    
                     
                    buttonEventSet.setText("Create Event Set");
                    buttonEventSet.setActionCommand("CreateEventSet"); 
                    buttonEventSet.addActionListener(this);
                    panelEvProgress.add(buttonEventSet);
                    
                     
                    labelevSet.setText("  Progress:  ");
                    labelevSet.setHorizontalAlignment(SwingConstants.CENTER);
                    labelevSet.setHorizontalTextPosition(SwingConstants.CENTER);
                    panelEvProgress.add(labelevSet);
                    panelEvProgress.add(progressEventSet);
                }
                panelEventSet.add(panelEvProgress, BorderLayout.SOUTH);                  

            }
            paneOpts.addTab("Event Set", panelEventSet);
            
             
            {
                panelAnalyze.setLayout(new BorderLayout());

                 
                labelStatInf.setText("Statistical Inference");
                labelStatInf.setHorizontalAlignment(SwingConstants.CENTER);
                panelAnalyze.add(labelStatInf, BorderLayout.NORTH);

                 
                {
                    panelMethods.setLayout(new BoxLayout(panelMethods, BoxLayout.Y_AXIS));
                    
                     
                    radioCrossEnt.setText("Cross Entropy");
                    radioCrossEnt.setActionCommand("crossentropy");
                    panelMethods.add(radioCrossEnt);
                    
                     
                    radioLZW.setText("LZW");
                    radioLZW.setActionCommand("lzw");
                    panelMethods.add(radioLZW);
                }
                panelAnalyze.add(panelMethods, BorderLayout.WEST);

                 
                {
                    panelAnalProg.setLayout(new BoxLayout(panelAnalProg, BoxLayout.X_AXIS));
                    
                     
                    buttonAnalyze.setText("Analyze");
                    buttonAnalyze.addActionListener(this);
                    panelAnalProg.add(buttonAnalyze);
                    
                     
                    labelAnalProg.setText("  Progress:  ");
                    labelAnalProg.setHorizontalAlignment(SwingConstants.CENTER);
                    labelAnalProg.setHorizontalTextPosition(SwingConstants.CENTER);
                    panelAnalProg.add(labelAnalProg);
                    panelAnalProg.add(progressAnalysis);
                }
                panelAnalyze.add(panelAnalProg, BorderLayout.SOUTH);

                listResults.setEnabled(false);
                 
                {
                    scrollPane3.setViewportView(listResults);
                }
                panelAnalyze.add(scrollPane3, BorderLayout.CENTER);
            }
            paneOpts.addTab("Analyze", panelAnalyze);
            
        }
        add(paneOpts, BorderLayout.CENTER);

         
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(radioKnown);
        buttonGroup1.add(radioUnknown);

         
        buttonGroup2 = new ButtonGroup();
        buttonGroup2.add(radioCrossEnt);
        buttonGroup2.add(radioLZW);
    } 

"""