"""
Model Manager — Manages local LLMs for Java test generation.

Usage:
    from model_manager import ModelManager
    manager = ModelManager()
    code = manager.run_from_file("Qwen_Qwen3-0.5B", "output/prompt.txt")
"""

import gc
import json
import os
import re
from pathlib import Path

from transformers import AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import snapshot_download
from dotenv import load_dotenv
from prompt_manager import PromptManager

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")
BASE_DIR = Path(__file__).resolve().parent


class ModelManager:
    """Manages local LLMs for test generation from extractor-produced prompts."""

    def __init__(self):
        self.models_dir = BASE_DIR / "models"
        self._loaded_model_name = None
        self._model = None
        self._tokenizer = None

    def download_model(self, hf_model_id: str) -> Path:
        """Downloads a model from Hugging Face and saves it under models/."""
        if not HF_TOKEN:
            raise ValueError("HF_TOKEN is not set in environment variables.")

        self.models_dir.mkdir(exist_ok=True)
        target_dir = self.models_dir / hf_model_id.replace("/", "_")

        if target_dir.exists():
            print(f"Model already exists at {target_dir}")
            return target_dir

        print(f"Downloading model {hf_model_id}...")
        snapshot_download(repo_id=hf_model_id, local_dir=target_dir, token=HF_TOKEN)
        return target_dir

    def run_model(self, model_name: str, prompt: str) -> str:
        """Loads the model and generates text from the prompt.

        Args:
            model_name: Model directory name inside models/.
            prompt: Input text for the model.

        Returns:
            Text generated by the model.
        """
        import torch

        model_path = self.models_dir / model_name

        if not model_path.exists():
            raise ValueError(f"Model not found at {model_path}")

        if self._loaded_model_name != model_name:
            self._model = None
            self._tokenizer = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            print(f"Loading model from {model_path}...")
            self._tokenizer = AutoTokenizer.from_pretrained(str(model_path))
            self._model = AutoModelForCausalLM.from_pretrained(
                str(model_path),
                dtype="auto",
                device_map="auto",
            )
            self._loaded_model_name = model_name

        print("Running model...")
        system_prompt = PromptManager().get_system_prompt()
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]
        text = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
        model_inputs = self._tokenizer([text], return_tensors="pt").to(self._model.device)

        generated_ids = self._model.generate(
            **model_inputs,
            max_new_tokens=2048,
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

        content = self._tokenizer.decode(output_ids, skip_special_tokens=True).strip("\n")
        return content

    def extract_java_code(self, raw_output: str) -> str:
        """Extracts only the Java code from the model's raw output."""
        fenced = re.search(r"```(?:java)?\s*\n(.*?)```", raw_output, re.DOTALL)
        if fenced:
            return fenced.group(1).strip()

        java_start = re.search(
            r"^(import\s+[\w.]+;|public\s|class\s|interface\s|enum\s|@[\w]+)",
            raw_output,
            re.MULTILINE,
        )
        if java_start:
            return raw_output[java_start.start():].strip()

        return raw_output.strip()

    def run_from_file(self, model_name: str, prompt_file: str, output_file: str = None) -> str:
        """Reads a prompt from a .txt file and runs it through the model.

        Args:
            model_name: Model directory name.
            prompt_file: Path to the .txt prompt file (e.g. output/0007_DocumentSet_wordFrequency.txt).
            output_file: Optional path to save the generated code.

        Returns:
            Generated Java code.
        """
        prompt_path = Path(prompt_file)
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_file}")

        prompt = prompt_path.read_text(encoding="utf-8")
        raw_output = self.run_model(model_name, prompt)
        code = self.extract_java_code(raw_output)

        if output_file:
            out_path = Path(output_file)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(code, encoding="utf-8")
            print(f"Code saved to {out_path}")

        return code

    def run_batch(self, model_name: str, input_dir: str, output_dir: str, max_files: int = 100):
        """Runs the model over all .txt prompt files in a directory.

        Args:
            model_name: Model directory name.
            input_dir: Directory containing .txt prompt files.
            output_dir: Output directory for generated tests.
            max_files: Maximum number of files to process.
        """
        in_path = Path(input_dir)
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        prompt_files = sorted(in_path.glob("*.txt"))[:max_files]
        results = []

        for i, pf in enumerate(prompt_files):
            print(f"\n[{i + 1}/{len(prompt_files)}] Processing {pf.name}...")
            try:
                out_file = out_path / pf.name.replace(".txt", ".java")
                code = self.run_from_file(model_name, str(pf), str(out_file))
                results.append({"file": pf.name, "output": str(out_file), "status": "ok", "length": len(code)})
            except Exception as e:
                print(f"  ERROR: {e}")
                results.append({"file": pf.name, "status": "error", "error": str(e)})

        meta_path = out_path / "batch_results.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

        ok = sum(1 for r in results if r["status"] == "ok")
        print(f"\n[Batch] {ok}/{len(prompt_files)} tests generated in '{output_dir}'")
        print(f"[Batch] Metadata: {meta_path}")
